#!/usr/bin/env ruby
require "slack_goodies"

cli = SlackGoodies::Cli.new

mailaddr_regexp=cli.get(:mail)
channel_name=cli.get(:channel)

begin
  sl = SlackGoodies::Connection.new
rescue =>e
  puts "SlackConnectionError #{e.message}"
  exit
end

dryrun="[dryrun] " if cli.get(:dryrun) 

channel_data = sl.channelname2channeldata(channel_name)
if channel_data.nil? then
  puts "#{channel_name} はありませんでした"
  exit
end
if channel_data['is_archived'] == "true" then
  puts "#{channel_name} はアーカイブ済みです"
  exit
end
puts "以下のチャンネルに対して招待を行います"
puts "Channel Name: #{channel_data['name']}"
puts "#{channel_data['purpose']['value']}"

puts "\n以下のアカウントをチャンネルに招待します"
sl.email2userdata(mailaddr_regexp).each do |user|
  puts "#{dryrun}#{user["real_name"]}(#{user["profile"]["email"]})"
end
