#!/usr/bin/env ruby
require "slack_goodies"
sl = SlackGoodies::Connection.new
cmd = SlackGoodies::Cli.new

begin
  sl = SlackGoodies::Connection.new
rescue =>e
  p e.message
end

cmd = SlackGoodies::Cli.new
sl.email2userdata(mailaddr_regexp).each do |user|
  puts "#{user["name"]} #{user["profile"]["email"]}"
end
