#!/usr/bin/env ruby
require "slack_goodies"

cli = SlackGoodies::Cli.new

mailaddr_regexp=cli.get(:mail)
channel_name=cli.get(:channel)

begin
  sl = SlackGoodies::Connection.new
rescue =>e
  puts "SlackConnectionError #{e.message}"
  exit
end

cmd = SlackGoodies::Cli.new
sl.email2userdata(mailaddr_regexp).each do |user|
  puts "#{user["name"]} #{user["profile"]["email"]}"
end
